Add pdf reports, markdown overview and analyses for the first basic benchmark done on my pc
stratum-mining/benchmarking-tool pull request #37
Opened 2024-08-02 11:51 UTC by GitGab19

Closes #34

2024-08-03 16:22 UTC, Shourya742 requested changes
Completed the initial reading. I will proofread soon. This review has clarified the benchmarking tool's overview and experimental metrics.

2024-08-07 18:14 UTC, marathon-gary commented on docs/benchmarking-tool-overview.md
> +        * _Description_: it tracks metrics about blocks mined by the miner(s) used to benchmark SV1
```suggestion
        * _Description_: Tracks metrics about blocks mined by the miner(s) used to benchmark SV1
```

2024-08-07 18:14 UTC, marathon-gary commented on docs/benchmarking-tool-overview.md
> +        * _Data Collection Method_: a SV1 custom proxy located between the miner and the SV1 Pool forwards all the traffic and analyze it, extracting the shares metrics
`A SV1...` is grammatically correct.

2024-08-07 18:15 UTC, marathon-gary commented on docs/benchmarking-tool-overview.md
> +        * _Description_: it tracks metrics about shares submitted by the miner(s) used to benchmark SV2
```suggestion
        * _Description_: Tracks shares submitted by the miner(s) used to benchmark SV2
```

2024-08-07 20:05 UTC, marathon-gary commented on docs/benchmarking-tool-overview.md
> +        * _Description_: it tracks metrics about blocks mined by the miner(s) used to benchmark SV2
```suggestion
        * _Description_: Tracks metrics about blocks mined by the miner(s) used to benchmark SV2
```

2024-08-08 12:40 UTC, marathon-gary commented
PDF generation of the overview should be in a README, imho. PDF won't age well unless we have some CI/CD that generates when commits are added. just my two sats

2024-08-11 08:05 UTC, GitGab19 commented
> PDF generation of the overview should be in a README, imho. PDF won't age well unless we have some CI/CD that generates when commits are added. just my two sats

Could you elaborate more?

2024-08-12 12:51 UTC, marathon-gary commented
> > PDF generation of the overview should be in a README, imho. PDF won't age well unless we have some CI/CD that generates when commits are added. just my two sats
> 
> Could you elaborate more? Should we label them with tool version? So that it will be clear in the future for everyone (?)

Originally my comment was intended to deter having a PDF in the repo and instead to just provide instructions for generating a PDF, however, after reading it through more comprehensively, I think the PDF is fine to stay as an example and initial documentation of findings.

2024-08-12 12:52 UTC, marathon-gary approved these changes

2024-08-12 15:01 UTC, Shourya742 approved these changes
ACK 4bbd76664c71d9a10a426fa8cfcd10aff632c737

2024-08-12 15:03 UTC, merged